@startuml

title Data model

hide circle
entity "Consumer"{
(PK) id
--
name
surname
age
(FK) city
}

entity "Thermometr"{
(PK) city
--
date
}

entity "Trainer"{
(PK) id
--
name
(FK) surname
expirience
(FK) plans
}

Consumer --{ Trainer
Thermometr --{ Consumer

@enduml
