@startuml

title Conditional - Activity Diagram measurements() 

start

:ПП починає пошук температури\nзгідно з вхідними даними;


if (Користувач указав місто?) then (так)
  if (Чи є дані по цьому місту?) then (так)
    : Вивести дані про температуру;
  else (ні)
    : Помилка: Відсутні дані по цьому місту!;
  endif
else (ні)
  :Помилка: Вкажіть місто!;
endif

stop

@enduml
