@startuml

title PlantUML
left to right direction
skinparam packageStyle rectangle
actor Користувач
rectangle {
Користувач --> (Авторизувати користувача)
(Отримати температуру\n навколишнього середовища) .> (Авторизувати користувача) : include
}

@enduml
